name: CI
env:
  VK_VERSION: 1.2.170.0
on:
  push:
    branches:
      - master

jobs:
  Linux:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install required packages
        shell: bash
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y make gcc g++ mesa-common-dev libglu1-mesa-dev libxxf86dga-dev libxxf86vm-dev libasound2-dev libx11-dev libxcb1-dev
      - name: Download and Install Vulkan SDK
        shell: bash
        run: |
          curl -L -v -o vulkansdk-linux-x86_64-$VK_VERSION.tar.gz -O https://sdk.lunarg.com/sdk/download/$VK_VERSION/linux/vulkan_sdk.tar.gz?Human=true
          tar zxf vulkansdk-linux-x86_64-$VK_VERSION.tar.gz
      - name: Build vkQuake2 Debug
        shell: bash
        run: |
          export VULKAN_SDK=$GITHUB_WORKSPACE/$VK_VERSION/x86_64
          cd linux
          make clean debug
          cd ..
      - name: Upload vkQuake2 Debug artifacts
        uses: actions/upload-artifact@v2.1.3
        with:
          name: vkQuake2-Ubuntu-debug-x64
          path: |
            linux/debugx64
            !linux/debugx64/**/*.o
      - name: Build vkQuake2 Release
        shell: bash
        run: |
          export VULKAN_SDK=$GITHUB_WORKSPACE/$VK_VERSION/x86_64
          cd linux
          make clean release
          cd ..
      - name: Upload vkQuake2 Release artifacts
        uses: actions/upload-artifact@v2.1.3
        with:
          name: vkQuake2-Ubuntu-release-x64
          path: |
            linux/releasex64
            !linux/releasex64/**/*.o
  ARMv7:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build vkQuake2 ARMv7 Debug
        uses: uraimo/run-on-arch-action@v1.0.9
        with:
          architecture: armv7
          distribution: ubuntu18.04
          run: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get -qq update
            apt-get install -y make gcc g++ libvulkan-dev mesa-common-dev libglu1-mesa-dev libxxf86dga-dev libxxf86vm-dev libasound2-dev libx11-dev libxcb1-dev
            cd linux
            make debug
      - name: Build vkQuake2 ARMv7 Release
        uses: uraimo/run-on-arch-action@v1.0.9
        with:
          architecture: armv7
          distribution: ubuntu18.04
          run: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get -qq update
            apt-get install -y make gcc g++ libvulkan-dev mesa-common-dev libglu1-mesa-dev libxxf86dga-dev libxxf86vm-dev libasound2-dev libx11-dev libxcb1-dev
            cd linux
            make release
  AArch64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build vkQuake2 AArch64 Debug
        uses: uraimo/run-on-arch-action@v1.0.9
        with:
          architecture: aarch64
          distribution: ubuntu18.04
          run: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get -qq update
            apt-get install -y make gcc g++ libvulkan-dev mesa-common-dev libglu1-mesa-dev libxxf86dga-dev libxxf86vm-dev libasound2-dev libx11-dev libxcb1-dev
            cd linux
            make debug
      - name: Build vkQuake2 AArch64 Release
        uses: uraimo/run-on-arch-action@v1.0.9
        with:
          architecture: aarch64
          distribution: ubuntu18.04
          run: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get -qq update
            apt-get install -y make gcc g++ libvulkan-dev mesa-common-dev libglu1-mesa-dev libxxf86dga-dev libxxf86vm-dev libasound2-dev libx11-dev libxcb1-dev
            cd linux
            make release
  PPC64LE:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build vkQuake2 PPC64LE Debug
        uses: uraimo/run-on-arch-action@v1.0.9
        with:
          architecture: ppc64le
          distribution: ubuntu18.04
          run: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get -qq update
            apt-get install -y make gcc g++ libvulkan-dev mesa-common-dev libglu1-mesa-dev libxxf86dga-dev libxxf86vm-dev libasound2-dev libx11-dev libxcb1-dev
            cd linux
            make debug
      - name: Build vkQuake2 PPC64LE Release
        uses: uraimo/run-on-arch-action@v1.0.9
        with:
          architecture: ppc64le
          distribution: ubuntu18.04
          run: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get -qq update
            apt-get install -y make gcc g++ libvulkan-dev mesa-common-dev libglu1-mesa-dev libxxf86dga-dev libxxf86vm-dev libasound2-dev libx11-dev libxcb1-dev
            cd linux
            make release
  MacOS:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Download and Install Vulkan SDK
        run: |
          curl -L -v -o vulkansdk-macos-$VK_VERSION.dmg -O https://sdk.lunarg.com/sdk/download/$VK_VERSION/mac/vulkan_sdk.dmg?Human=true
          hdiutil mount vulkansdk-macos-$VK_VERSION.dmg
          cp -R "/Volumes/vulkansdk-macos-$VK_VERSION/" $GITHUB_WORKSPACE/vulkansdk-macos-$VK_VERSION
          hdiutil unmount "/Volumes/vulkansdk-macos-$VK_VERSION"  
      - name: Build vkQuake2 Debug
        run: |
          export VULKAN_SDK=$GITHUB_WORKSPACE/vulkansdk-macos-$VK_VERSION
          cd macos
          make clean-xcode debug-xcode
          cd ..
      - name: Upload vkQuake2 Debug artifacts
        uses: actions/upload-artifact@v2.1.3
        with:
          name: vkQuake2-MacOS-debug-x64
          path: |
            macos/vkQuake2
            !macos/vkQuake2/**/*.o
      - name: Build vkQuake2 Release
        run: |
          export VULKAN_SDK=$GITHUB_WORKSPACE/vulkansdk-macos-$VK_VERSION
          cd macos
          make clean-xcode release-xcode
          cd ..
      - name: Upload vkQuake2 Release artifacts
        uses: actions/upload-artifact@v2.1.3
        with:
          name: vkQuake2-MacOS-release-x64
          path: |
            macos/vkQuake2
            !macos/vkQuake2/**/*.o
  Windows:
    env:
      VULKAN_SDK: c:\VulkanSDK\%VK_VERSION%
    runs-on: windows-latest

    steps:
    - uses: microsoft/setup-msbuild@v1.0.2
    - uses: actions/checkout@v2

    - name: Download Vulkan SDK
      shell: powershell
      run: curl -v -o VulkanSDK.exe https://sdk.lunarg.com/sdk/download/$env:VK_VERSION/windows/vulkan_sdk.exe?Human=true
    - name: Install Vulkan SDK
      shell: cmd
      run: .\VulkanSDK.exe /S
    - name: Build vkQuake2 Debug (x86)
      run: msbuild quake2.sln /m /t:Rebuild /p:Configuration=Debug /p:Platform=x86
    - name: Upload vkQuake2 Debug (x86) artifacts
      uses: actions/upload-artifact@v2.1.3
      with:
        name: vkQuake2-Windows-debug-x86
        path: |
          Quake2
          !Quake2/**/*.obj
          !Quake2/**/*.exp
          !Quake2/**/*.ilk
          !Quake2/**/*.lib
          !Quake2/**/*.pdb
          !Quake2/**/*.iobj
          !Quake2/**/*.ipdb
    - name: Build vkQuake2 Release (x86)
      run: msbuild quake2.sln /m /t:Rebuild /p:Configuration=Release /p:Platform=x86
    - name: Upload vkQuake2 Release (x86) artifacts
      uses: actions/upload-artifact@v2.1.3
      with:
        name: vkQuake2-Windows-release-x86
        path: |
          Quake2
          !Quake2/**/*.obj
          !Quake2/**/*.exp
          !Quake2/**/*.ilk
          !Quake2/**/*.lib
          !Quake2/**/*.pdb
          !Quake2/**/*.iobj
          !Quake2/**/*.ipdb
    - name: Build vkQuake2 Debug (x64)
      run: msbuild quake2.sln /m /t:Rebuild /p:Configuration=Debug /p:Platform=x64
    - name: Upload vkQuake2 Debug (x64) artifacts
      uses: actions/upload-artifact@v2.1.3
      with:
        name: vkQuake2-Windows-debug-x64
        path: |
          Quake2
          !Quake2/**/*.obj
          !Quake2/**/*.exp
          !Quake2/**/*.ilk
          !Quake2/**/*.lib
          !Quake2/**/*.pdb
          !Quake2/**/*.iobj
          !Quake2/**/*.ipdb
    - name: Build vkQuake2 Release (x64)
      run: msbuild quake2.sln /m /t:Rebuild /p:Configuration=Release /p:Platform=x64
    - name: Upload vkQuake2 Release (x64) artifacts
      uses: actions/upload-artifact@v2.1.3
      with:
        name: vkQuake2-Windows-release-x64
        path: |
          Quake2
          !Quake2/**/*.obj
          !Quake2/**/*.exp
          !Quake2/**/*.ilk
          !Quake2/**/*.lib
          !Quake2/**/*.pdb
          !Quake2/**/*.iobj
          !Quake2/**/*.ipdb
